#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Render the Harbor compatibility table into README.md from e2e result files.

Consumes one result JSON per harbor-compat matrix leg (see
.github/workflows/harbor-compat.yml), each shaped:

    {"chart": "1.19.1", "app": "2.15.1", "status": "pass", "date": "2026-06-21"}

and splices a version-sorted markdown table between the HARBOR-COMPAT markers in
README.md. Floor = lowest-versioned *passing* Harbor; ceiling = highest passing
(ADR-0020). Idempotent: re-running with the same inputs leaves README byte-identical.

Usage: render-compat-table.py '<results-glob>' <readme-path>
"""
import glob
import json
import sys

BEGIN_PREFIX = "<!-- BEGIN HARBOR-COMPAT"
BEGIN_LINE = (
    BEGIN_PREFIX
    + " (generated by .github/workflows/harbor-compat.yml — do not edit by hand) -->"
)
END_LINE = "<!-- END HARBOR-COMPAT -->"


def semver(v):
    """Parse 'X.Y.Z' into a comparable tuple; unknown/garbage sorts lowest."""
    try:
        return tuple(int(x) for x in v.split(".")[:3])
    except (ValueError, AttributeError):
        return (-1,)


def main(results_glob, readme_path):
    rows = []
    for path in sorted(glob.glob(results_glob)):
        with open(path, encoding="utf-8") as fh:
            rows.append(json.load(fh))
    if not rows:
        print(f"no result files matched {results_glob!r}", file=sys.stderr)
        return 1

    rows.sort(key=lambda r: semver(r["app"]), reverse=True)
    passing = [semver(r["app"]) for r in rows if r["status"] == "pass"]
    floor = min(passing, default=None)
    ceiling = max(passing, default=None)

    lines = [
        BEGIN_LINE,
        "",
        "| Harbor | Chart | Tested | Last run (UTC) |",
        "| --- | --- | --- | --- |",
    ]
    for r in rows:
        v = semver(r["app"])
        tag = ""
        if v == ceiling:
            tag = " (ceiling)"
        elif v == floor:
            tag = " (floor)"
        mark = "✅" if r["status"] == "pass" else "❌"
        lines.append(f"| {r['app']}{tag} | {r['chart']} | {mark} | {r['date']} |")
    lines += ["", END_LINE]
    table = "\n".join(lines)

    with open(readme_path, encoding="utf-8") as fh:
        content = fh.read()
    start = content.find(BEGIN_PREFIX)
    end = content.find(END_LINE)
    if start == -1 or end == -1:
        print(f"HARBOR-COMPAT markers not found in {readme_path}", file=sys.stderr)
        return 1
    end += len(END_LINE)
    content = content[:start] + table + content[end:]
    with open(readme_path, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"rendered {len(rows)} rows; floor={floor} ceiling={ceiling}")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        sys.exit(2)
    sys.exit(main(sys.argv[1], sys.argv[2]))
