//go:build !ignore_autogenerated

// Copyright 2026 The Aetherize Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborAccess) DeepCopyInto(out *HarborAccess) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborAccess.
func (in *HarborAccess) DeepCopy() *HarborAccess {
	if in == nil {
		return nil
	}
	out := new(HarborAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HarborAccess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborAccessList) DeepCopyInto(out *HarborAccessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HarborAccess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborAccessList.
func (in *HarborAccessList) DeepCopy() *HarborAccessList {
	if in == nil {
		return nil
	}
	out := new(HarborAccessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HarborAccessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborAccessSpec) DeepCopyInto(out *HarborAccessSpec) {
	*out = *in
	out.TrustPolicy = in.TrustPolicy
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]ProjectPermission, len(*in))
		copy(*out, *in)
	}
	out.TokenTTL = in.TokenTTL
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborAccessSpec.
func (in *HarborAccessSpec) DeepCopy() *HarborAccessSpec {
	if in == nil {
		return nil
	}
	out := new(HarborAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarborAccessStatus) DeepCopyInto(out *HarborAccessStatus) {
	*out = *in
	if in.Robot != nil {
		in, out := &in.Robot, &out.Robot
		*out = new(RobotRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarborAccessStatus.
func (in *HarborAccessStatus) DeepCopy() *HarborAccessStatus {
	if in == nil {
		return nil
	}
	out := new(HarborAccessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectPermission) DeepCopyInto(out *ProjectPermission) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectPermission.
func (in *ProjectPermission) DeepCopy() *ProjectPermission {
	if in == nil {
		return nil
	}
	out := new(ProjectPermission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotRef) DeepCopyInto(out *RobotRef) {
	*out = *in
	if in.LastRotated != nil {
		in, out := &in.LastRotated, &out.LastRotated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotRef.
func (in *RobotRef) DeepCopy() *RobotRef {
	if in == nil {
		return nil
	}
	out := new(RobotRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustPolicy) DeepCopyInto(out *TrustPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustPolicy.
func (in *TrustPolicy) DeepCopy() *TrustPolicy {
	if in == nil {
		return nil
	}
	out := new(TrustPolicy)
	in.DeepCopyInto(out)
	return out
}
