{{- include "harbor-bridge.validateRequiredValues" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "harbor-bridge.bridge.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harbor-bridge.bridge.labels" . | nindent 4 }}
automountServiceAccountToken: true
