apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor-bridge.bridge.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harbor-bridge.bridge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "harbor-bridge.bridge.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
