//go:build !ignore_autogenerated

// Copyright 2026 The Aetherize Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusAccess) DeepCopyInto(out *NexusAccess) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusAccess.
func (in *NexusAccess) DeepCopy() *NexusAccess {
	if in == nil {
		return nil
	}
	out := new(NexusAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NexusAccess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusAccessList) DeepCopyInto(out *NexusAccessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NexusAccess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusAccessList.
func (in *NexusAccessList) DeepCopy() *NexusAccessList {
	if in == nil {
		return nil
	}
	out := new(NexusAccessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NexusAccessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusAccessSpec) DeepCopyInto(out *NexusAccessSpec) {
	*out = *in
	out.ServiceAccountRef = in.ServiceAccountRef
	out.TrustPolicy = in.TrustPolicy
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = make([]RepositoryGrant, len(*in))
		copy(*out, *in)
	}
	out.TokenTTL = in.TokenTTL
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusAccessSpec.
func (in *NexusAccessSpec) DeepCopy() *NexusAccessSpec {
	if in == nil {
		return nil
	}
	out := new(NexusAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusAccessStatus) DeepCopyInto(out *NexusAccessStatus) {
	*out = *in
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(UserRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusAccessStatus.
func (in *NexusAccessStatus) DeepCopy() *NexusAccessStatus {
	if in == nil {
		return nil
	}
	out := new(NexusAccessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryGrant) DeepCopyInto(out *RepositoryGrant) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryGrant.
func (in *RepositoryGrant) DeepCopy() *RepositoryGrant {
	if in == nil {
		return nil
	}
	out := new(RepositoryGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountRef) DeepCopyInto(out *ServiceAccountRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountRef.
func (in *ServiceAccountRef) DeepCopy() *ServiceAccountRef {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustPolicy) DeepCopyInto(out *TrustPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustPolicy.
func (in *TrustPolicy) DeepCopy() *TrustPolicy {
	if in == nil {
		return nil
	}
	out := new(TrustPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserRef) DeepCopyInto(out *UserRef) {
	*out = *in
	if in.LastRotated != nil {
		in, out := &in.LastRotated, &out.LastRotated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserRef.
func (in *UserRef) DeepCopy() *UserRef {
	if in == nil {
		return nil
	}
	out := new(UserRef)
	in.DeepCopyInto(out)
	return out
}
